name: Windows 10 Tunnel with Serveo

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Setup Remote Desktop
      run: |
        # Enable Remote Desktop on the Windows machine.
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        # Enable Windows Firewall rules for Remote Desktop.
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Require user authentication for RDP connections.
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # Set the password for the 'runneradmin' user.
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
      
    - name: Create Tunnel with Serveo
      run: |
        # This SSH command creates a reverse tunnel.
        # Connections to serveo.net on port 3389 will be forwarded to the local port 3389.
        ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net
